# Generated by Django 3.0.8 on 2020-07-22 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.CharField(blank=True, default='', max_length=255)),
                ('mrds_url', models.URLField(blank=True, default='', max_length=255)),
                ('mrds_id', models.CharField(blank=True, default='', max_length=255)),
                ('mas_id', models.CharField(blank=True, default='', max_length=255)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('com_type', models.CharField(blank=True, choices=[('N', 'Non-metallic'), ('M', 'Metallic'), ('B', 'Both'), ('', '----------')], default='', max_length=255)),
                ('dep_type', models.CharField(blank=True, default='', max_length=255)),
                ('prod_size', models.CharField(blank=True, default='', max_length=50)),
                ('ore', models.TextField(blank=True, default='')),
                ('gangue', models.TextField(blank=True, default='')),
                ('other_matl', models.TextField(blank=True, default='')),
                ('orebody_fm', models.TextField(blank=True, default='')),
                ('geo_model', models.TextField(blank=True, default='', verbose_name='Model')),
                ('alteration', models.TextField(blank=True, default='')),
                ('conc_proc', models.TextField(blank=True, default='')),
                ('alt_previous_names', models.TextField(blank=True, default='')),
                ('ore_control', models.TextField(blank=True, default='')),
                ('reporter', models.TextField(blank=True, default='')),
                ('hrock_unit', models.TextField(blank=True, default='')),
                ('hrock_type', models.TextField(blank=True, default='')),
                ('arock_unit', models.TextField(blank=True, default='')),
                ('arock_type', models.TextField(blank=True, default='')),
                ('structure', models.TextField(blank=True, default='')),
                ('tectonic', models.TextField(blank=True, default='')),
                ('ref', models.TextField(blank=True, default='')),
                ('yfp_ba', models.TextField(blank=True, default='')),
                ('yr_fst_prd', models.TextField(blank=True, default='')),
                ('ylp_ba', models.TextField(blank=True, default='')),
                ('yr_lst_prd', models.TextField(blank=True, default='')),
                ('dy_ba', models.TextField(blank=True, default='')),
                ('disc_yr', models.TextField(blank=True, default='')),
                ('prod_yrs', models.TextField(blank=True, default='')),
                ('discr', models.TextField(blank=True, default='')),
                ('commodity_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_sites', to='mrds.Commodity')),
                ('commodity_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_sites', to='mrds.Commodity')),
                ('commodity_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tertiary_sites', to='mrds.Commodity')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrds.County')),
                ('development_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrds.DevelopmentStatus')),
                ('operation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrds.OperationType')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrds.State')),
            ],
        ),
    ]
