# Generated by Django 3.0.8 on 2020-07-23 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrds', '0003_auto_20200722_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrds.WorkType'),
        ),
        migrations.AlterField(
            model_name='site',
            name='com_type',
            field=models.CharField(blank=True, choices=[('N', 'Non-metallic'), ('', '----------'), ('B', 'Both'), ('M', 'Metallic')], default='', max_length=255),
        ),
    ]
